// Root ESLint flat config. The Nuxt-aware base is generated by @nuxt/eslint via
// `nuxt prepare` (run automatically by the `lint` script) so auto-imported
// globals (ref, computed, defineNuxtConfig, useState, ...) resolve correctly.
import withNuxt from "./apps/web/.nuxt/eslint.config.mjs";

export default withNuxt(
  {
    ignores: [
      "**/node_modules/**",
      "**/.nuxt/**",
      "**/.output/**",
      "**/.wrangler/**",
      "**/dist/**",
      "**/test-results/**",
      "**/playwright-report/**",
      "pnpm-lock.yaml",
      "docs/**"
    ]
  },
  {
    files: ["**/*.{ts,vue}"],
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-imports": "error",
      "vue/multi-word-component-names": "off",
      "vue/no-v-html": "error",
      // Align with Prettier, which self-closes void elements like <input />.
      "vue/html-self-closing": [
        "error",
        {
          html: { void: "any", normal: "always", component: "always" },
          svg: "always",
          math: "always"
        }
      ]
    }
  }
);
